import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import MovieListApp from './movieListApp'
import Footer from '@/components/layout/Footer'
import SideMenu from '@/components/layout/SideMenu'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <div className='flex flex-col h-screen justify-between
      bg-gradient-to-r from-slate-900 to-indigo-900'>
      <aside className='flex flex-col fixed h-screen  justify-center'>
        <SideMenu />
      </aside>
      <header className="h-100"> 
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      </header>
      <main className="mb-auto h-auto ml-16">
        <MovieListApp/>
      </main>
    
      <footer className="h-200">
        <Footer title="2023 Stunners Art, LLC  All Rights Reserved." />
      </footer>
       </div>
    </>
  )
}
